amsterdam/Controllers/RecommendationController.cs
using amsterdam.Models;
using Microsoft.AspNetCore.Mvc;

namespace amsterdam.Controllers
{
    public class RecommendationController : Controller
    {
        private readonly ApplicationDbContext _db;
        public RecommendationController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            List<recommendation> objList = _db.recommendations.ToList();
            return View(objList);
        }
        public IActionResult Update_Insert(int? id)
        {
            recommendation obj = new recommendation();
            if (id == null)
            {
                //create
                return View(obj);
            }
            //update
            obj = _db.recommendations.FirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        [HttpPost]
        public IActionResult Update_Insert(recommendation obj)
        {

            if (ModelState.IsValid)
            {
                if (obj.Id == 0)
                {
                    //create
                    _db.recommendations.Add(obj);
                }
                else
                {
                    _db.recommendations.Update(obj);
                }
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(obj);
        }
        public IActionResult Delete(int id)
        {
            var obj = _db.recommendations.FirstOrDefault(u => u.Id == id);
            _db.recommendations.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

amsterdam/Controllers/ReservationController.cs
using amsterdam.Models;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;

namespace amsterdam.Controllers
{
    public class ReservationController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ReservationController(ApplicationDbContext db)
        {
            _db = db;
        }
        [HttpGet]
        public IActionResult HotelApply()
        {
            return View();
        }
        [HttpPost]
        public IActionResult HotelApply(Hotel hotel)
        {
            if (string.IsNullOrEmpty(hotel.Name))
            {
                ModelState.AddModelError(nameof(hotel.Name), "Name is compulsory field.");
            }
            if (string.IsNullOrEmpty(hotel.Phone))
            {
                ModelState.AddModelError(nameof(hotel.Phone), "Phone number is compulsory field.");
            }
            else
            {
                if (!hotel.Phone.Contains("+"))
                {
                    ModelState.AddModelError(nameof(hotel.Email), "Phone number is not right format.");
                }
            }
            if (string.IsNullOrEmpty(hotel.Email))
            {
                ModelState.AddModelError(nameof(hotel.Email), "Email is compulsory field.");
            }
            else
            {
                if (!hotel.Email.Contains("@"))
                {
                    ModelState.AddModelError(nameof(hotel.Email), "Email address is not right format.");
                }
            }
            if (string.IsNullOrEmpty(hotel.CheckIn))
            {
                ModelState.AddModelError(nameof(hotel.CheckIn), "CheckIn compulsory field.");
            }
            else
            {
                if (!hotel.CheckIn.Contains("/"))
                {
                    ModelState.AddModelError(nameof(hotel.CheckIn), "CheckIn is not right format.");
                }
            }
            if (string.IsNullOrEmpty(hotel.CheckOut))
            {
                ModelState.AddModelError(nameof(hotel.CheckOut), "CheckOut compulsory field.");
            }
            else
            {
                if (!hotel.CheckOut.Contains("/"))
                {
                    ModelState.AddModelError(nameof(hotel.CheckOut), "CheckOut is not right format.");
                }
            }
            if (string.IsNullOrEmpty(hotel.NumberOfPerson.ToString()))
            {
                ModelState.AddModelError(nameof(hotel.NumberOfPerson), "NumberOfPerson compulsory field.");
            }
            else
            {
                if (hotel.NumberOfPerson < 1)
                {
                    ModelState.AddModelError(nameof(hotel.NumberOfPerson), "NumberOfPerson must not be less than 1.");
                }
            }

            if (ModelState.IsValid)
            {

                _db.hotels.Add(hotel);
                _db.SaveChanges();
                return View("HotelThanks", hotel);
            }
            else
            {
                return View();
            }

        }
        [HttpGet]
        public IActionResult PlaneApply()
        {
            return View();
        }
        [HttpPost]
        public IActionResult PlaneApply(Plane plane)
        {
            if (string.IsNullOrEmpty(plane.Name))
            {
                ModelState.AddModelError(nameof(plane.Name), "Name is compulsory field.");
            }
            if (string.IsNullOrEmpty(plane.Phone))
            {
                ModelState.AddModelError(nameof(plane.Phone), "Phone number is compulsory field.");
            }
            else
            {
                if (!plane.Phone.Contains("+"))
                {
                    ModelState.AddModelError(nameof(plane.Email), "Phone number is not right format.");
                }
            }
            if (string.IsNullOrEmpty(plane.Email))
            {
                ModelState.AddModelError(nameof(plane.Email), "Email is compulsory field.");
            }
            else
            {
                if (!plane.Email.Contains("@"))
                {
                    ModelState.AddModelError(nameof(plane.Email), "Email address is not right format.");
                }
            }
            if (string.IsNullOrEmpty(plane.DeparturePlace))
            {
                ModelState.AddModelError(nameof(plane.DeparturePlace), "Departure Place is compulsory field.");
            }
            if (string.IsNullOrEmpty(plane.DepartureDate))
            {
                ModelState.AddModelError(nameof(plane.DepartureDate), "Departure Date compulsory field.");
            }
            else
            {
                if (!plane.DepartureDate.Contains("/"))
                {
                    ModelState.AddModelError(nameof(plane.DepartureDate), "Departure Date is not right format.");
                }
            }
            if (string.IsNullOrEmpty(plane.NumberOfPerson.ToString()))
            {
                ModelState.AddModelError(nameof(plane.NumberOfPerson), "NumberOfPerson compulsory field.");
            }
            else
            {
                if (plane.NumberOfPerson < 1)
                {
                    ModelState.AddModelError(nameof(plane.NumberOfPerson), "NumberOfPerson must not be less than 1.");
                }
            }

            if (ModelState.IsValid)
            {
                _db.planes.Add(plane);
                _db.SaveChanges();
                return View("PlaneThanks", plane);
            }
            else
            {
                return View();
            }
        }
        public IActionResult HotelThanks()
        {
            return View();
        }
        public IActionResult PlaneThanks()
        {
            return View();
        }
    }
}

amsterdam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Amsterdam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        nav {
            height: 65px;
            width: 100%;
            background-color: rgb(103, 64, 36);
            text-decoration: none;
            box-sizing: border-box;
            padding-top: 15px;
            font-size: 18px;
            z-index: 100;
        }
            nav.logo {
                padding-top: 30px;
                float: left;
            }

        label.logo {
            color: white;
            font-size: 24px;
        }

        label i {
            padding-left: 20px;
        }

        nav a {
            text-decoration: none;
        }

        nav ul {
            float: right;
            margin-right: 20px;
        }

            nav ul li {
                display: inline-block;
                line-height: 50px;
                margin: -10px 10px;
            }

                nav ul li a {
                    text-transform: uppercase;
                    padding: 2px 13px;
                    color: white;
                    margin-top: 5px;
                }

        nav a:hover {
            background-color: rgb(192, 156, 109);
            border-radius: 3px;
            transition: .2s;
        }
        footer{
            background-color: rgb(103, 64, 36);
        }
    </style>
</head>
<body>
    <header>

        <nav class="navbar">
            <label class="logo"><i class="fas fa-hiking">BON VOYAGE</i></label>
            <ul>
                <li><a asp-area="" asp-controller="Home" asp-action="Index">HOME</a> </li>
                @RenderSection("section3",false)
                <li><a asp-area="" asp-controller="Reservation" asp-action="HotelApply">Hotel</a> </li>
                <li><a asp-area="" asp-controller="Reservation" asp-action="PlaneApply">Plane </a> </li>
            </ul>

        </nav>
    </header>

	@RenderSection("thanksSection",false)
    @RenderSection("thanksSection2",false)

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container" style="color: white;">
            &copy; @DateTime.Now.Year - Bon Voyage -Ayşenur-Hazal-Sinem <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

amsterdam/Views/Shared/_Partial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div id="reservation">
    <div>
        <a asp-area="" asp-controller="Reservation" asp-action="HotelApply">FIND HOTEL
            <br />
            <img src="https://images.pexels.com/photos/2467558/pexels-photo-2467558.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" />
        </a>
    </div>
    <div>
        <a asp-area="" asp-controller="Reservation" asp-action="PlaneApply">FIND FLIGHT
            <br />
            <img src="https://media.istockphoto.com/id/136881645/tr/foto%C4%9Fraf/xl-jet-airplane-landing-at-sunset.jpg?s=612x612&w=0&k=20&c=v6mpDwDgDsp8A02ru4gKZ-dAXCyu_lHg9ceLmUzWVik=" />
        </a>
    </div>
    <div>
        <a asp-area="" asp-controller="Recommendation" asp-action="Index">RECOMMENDATIONS
            <br />
            <img src="https://images.pexels.com/photos/4530183/pexels-photo-4530183.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" />
        </a>
    </div>
</div>